### ISSUE TITLE
Add "today" date as default

### ISSUE THREAD

**Issue by Set27** [npupko/exchanger#2]
When I'm using Exchanger, I mostly want to know the exchange rate for today. So I suggest to make "today" date as default, and add flag for "not today" date.
Example
`exchanger --amount 1000` will return 
```
# USD rate for 2023-11-15 is 3.15
# You received (in BYN): ....
```
In this example, Exchanger will use "today" date (when I create issue, today is 15 of November 2023)  
`exchanger --amount 1000 --date 2023-11-14` will return 
```
# USD rate for 2023-11-14 is 3.10
# You received (in BYN): ....
```

**Comment by npupko** [comment]
@Set27 Feel free to test it out!
